INSERT INTO jobs (id, title, description, location) VALUES
(1, 'Investment Banking Analyst - Asset Backed Securities', 'Analyze and structure asset-backed securities transactions.', 'New York, United States'),
(2, 'Investment Banking Associate - Private Equity & Fund Finance', 'Manage private equity and fund finance portfolios.', 'New York, United States'),
(3, 'Investment Banking Analyst - Net Asset Value Lending', 'Assess and manage net asset value lending opportunities.', 'New York, United States'),
(4, 'Investment Banking Associate - Corporate Advisory & Financing', 'Provide corporate advisory and financing solutions.', 'New York, United States'),
(5, 'Investment Banking Analyst - Technology Banking', 'Support technology sector clients with banking solutions.', 'San Francisco, United States'),
(6, 'Investment Banking Associate - CLO Banking', 'Manage collateralized loan obligation banking activities.', 'New York, United States'),
(7, 'Investment Banking Associate - Structured Finance - Real Estate', 'Structure and manage real estate finance transactions.', 'New York, United States'),
(8, 'Investment Banking Associate - Fund Finance Distribution', 'Distribute fund finance products to clients.', 'New York, United States'),
(9, 'Internship - Hedge Funds Credit Risk', 'Analyze credit risk for hedge fund clients.', 'New York, United States'),
(10, 'Investment Banking Associate - Energy Project Finance', 'Finance energy projects and manage related risks.', 'New York, United States'),
(11, 'Counsel – Litigation, Enforcement & Investigations', 'Provide legal counsel on litigation and investigations.', 'New York, United States'),
(12, 'Bernstein Research Management Associate', 'Assist in managing research operations at Bernstein.', 'New York, United States'),
(13, 'Vice President - Fund Finance Distribution', 'Lead fund finance distribution strategies.', 'New York, United States'),
(14, 'Java Developer', 'Develop and maintain Java-based applications.', 'Chicago, United States'),
(15, 'Business Auditor - Associate', 'Conduct audits of business operations and processes.', 'New York, United States'),
(16, 'Quantitative Finance Developer', 'Develop quantitative models for financial applications.', 'New York, United States'),
(17, 'Research Associate – US Biotechnology', 'Conduct research on US biotechnology sector.', 'New York, United States'),
(18, 'Operational Client Relationship Manager, Vice President', 'Manage client relationships and operational processes.', 'New York, United States'),
(19, 'Legal Counsel / Legal Documentation Negotiator', 'Negotiate and draft legal documentation.', 'New York, United States'),
(20, 'Vice President - Energy Project Finance Group', 'Lead energy project finance initiatives.', 'Houston, United States'),
(21, 'Software Engineer', 'Design, develop, and maintain software solutions for banking operations.', 'Paris, France'),
(22, 'Software Engineer', 'Develop scalable backend services for financial applications.', 'Bengaluru, India'),
(23, 'Specialist Software Engineer', 'Lead technical design and implementation of complex software systems.', 'Paris, France'),
(24, 'Specialist Software Engineer', 'Architect and optimize high-performance trading platforms.', 'Bengaluru, India'),
(25, 'Software Engineer', 'Collaborate with cross-functional teams to deliver innovative banking products.', 'New York, United States');
